services:
  - type: web
    name: gl-quality-goods
    env: node
    plan: free
    nodeVersion: 20
    buildCommand: npm install && NODE_ENV=production npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

